### ISSUE TITLE
Better use drawable selector

### ISSUE THREAD

**Issue by splundid** [akvelon/android-image-picker#1]
https://github.com/akvelon/android-image-picker/blob/cd3071c2edc141d16264f13593422b911e56a213/imagepicker/src/main/java/com/akvelon/imagepicker/PickerActivity.kt#L37-L38

It's probably better to use one selector drawable instead of multiple drawables with logic in code

**Comment by RustemMuzafarov** [comment]
Yeah, thanks, good idea. Will be done in 1.0.1
