### ISSUE TITLE
Diff utils would be helpful here

### ISSUE THREAD

**Issue by splundid** [akvelon/android-image-picker#2]
https://github.com/akvelon/android-image-picker/blob/cd3071c2edc141d16264f13593422b911e56a213/imagepicker/src/main/java/com/akvelon/imagepicker/PickerActivity.kt#L118

This code redraws the whole adapter even though some items may be intact

**Comment by RustemMuzafarov** [comment]
There is no need - all items have to be changed anyway, so DiffUtil won't make any difference.
