### ISSUE TITLE
Adapter is recreated on refresh

### ISSUE THREAD

**Issue by splundid** [akvelon/android-image-picker#3]
https://github.com/akvelon/android-image-picker/blob/cd3071c2edc141d16264f13593422b911e56a213/imagepicker/src/main/java/com/akvelon/imagepicker/PickerActivity.kt#L184

Adapter should be created on init

**Comment by RustemMuzafarov** [comment]
Actually, it's only created once during first initialization. Looks like the "refresh()" method name is slightly misleading.
