### ISSUE TITLE
Media store db is queried on the main thread

### ISSUE THREAD

**Issue by splundid** [akvelon/android-image-picker#4]
https://github.com/akvelon/android-image-picker/blob/cd3071c2edc141d16264f13593422b911e56a213/imagepicker/src/main/java/com/akvelon/imagepicker/PickerActivity.kt#L148

Better put this in background thread to avoid ui freezes

**Comment by RustemMuzafarov** [comment]
Yeah, thanks, I agree. Will be fixed in 1.0.1
